# Generated by Django 2.2 on 2019-07-09 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Languages', '0002_language_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brouser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brouser',
                'verbose_name_plural': 'Brousers',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('code', models.TextField()),
                ('result', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='BrouserSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brouser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Languages.Brouser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Languages.Post')),
            ],
            options={
                'verbose_name': 'BrouserSupport',
                'verbose_name_plural': 'BrouserSupports',
            },
        ),
    ]
