# Generated by Django 2.2 on 2019-07-09 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Languages', '0003_brouser_brousersupport_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prortamLanguage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='Languages.Language'),
            preserve_default=False,
        ),
    ]
