# Generated by Django 2.2 on 2019-07-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Languages', '0005_auto_20190710_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='icon',
            field=models.CharField(default='', max_length=50),
        ),
    ]
