# Generated by Django 2.2 on 2019-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Languages', '0006_language_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
