# Generated by Django 2.2 on 2019-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Languages', '0007_auto_20190713_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
